#Author: Chaluka Wanniarachchi
#Last updated: 2026/03/16 V1.1.1
#sysmonitorlv4 configuration file.
#these threshold values are configurable as your need.

#Thresholds (in percentage)
CPU_THRESHOLD=85
MEMORY_THRESHOLD=80
DISK_THRESHOLD=90

#Below number of times, it will recheck above thresholds for a alert 
ALERT_CONSECUTIVE=3

#Directory paths
LOG_DIR="/home/chaluka/sysmonitorlv4/logs"
ALERT_LOG="/home/chaluka/sysmonitorlv4/logs/alerts.log"
MAIN_LOG="/home/chaluka/sysmonitorlv4/logs/sysmonitor.log"

#Alert methos: "log" only for now
ALERT_METHOD="log"

#Project name to be appears in log entries
PROJECT_NAME="sysmonitorlv4"
